[workspace]
members = [ "auto-gippity","rust-autogpt"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["rust-autogpt"]
resolver = "2"


[workspace.dependencies]
